apiVersion: v2
name: saleor
description: Saleor Graphql E-commerce Helm Chart
type: application
version: 0.2.14
appVersion: 0.4.0
dependencies:
- name: storefront
  version: ^0.2.14
  repository: file://../storefront
- name: dashboard
  version: ^0.2.14
  repository: file://../dashboard
- name: postgresql
  version: ^8.10.5
  repository: https://charts.bitnami.com/bitnami
  condition: global.postgresql.enabled
- name: redis
  version: ^10.7.1
  repository: https://charts.bitnami.com/bitnami