apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor.fullname" . }}
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saleor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
