apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-worker
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
spec:
{{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
    {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saleor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      volumes:
        - name: service-account
          secret:
            secretName: {{ .Values.GACRedentialsSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["celery", "-A", "saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel={{ .Values.worker.loglevel }}"]
          env:
            - name: REDIS_URL
              value: {{ template "saleor.redis" . }}/1
            - name: CELERY_BROKER_URL
              value: {{ template "saleor.redis" . }}/0
            - name: CELERY_RESULT_BACKEND
              value: {{ template "saleor.redis" . }}/0
            - name: DEFAULT_FROM_EMAIL
              value: {{ .Values.defaultFromEmail }}
            - name: DATABASE_URL
              value: {{ template "saleor.postgresql" . }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.key }}
            - name: GS_MEDIA_BUCKET_NAME
              value: {{ .Values.bucketName }}
            - name: GS_STORAGE_BUCKET_NAME
              value: {{ .Values.bucketName }}
            - name: ALLOWED_CLIENT_HOSTS
              value: {{ .Values.allowedClientHost }}
            - name: DEBUG
              value: "{{ .Values.debug }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.GACRedentialsPath }}
            - name: ENABLE_SSL
              value: "{{ .Values.enableSSL }}"
            - name: EMAIL_URL
              value: smtp://{{ .Values.MAILJET_USERNAME }}:{{ .Values.MAILJET_PASSWORD }}@{{ .Values.MAILJET_SMTP_SERVER }}:587/?tls=True
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret }}
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret }}
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret }}
                  key: database
          volumeMounts:
            - name: service-account
              mountPath: {{ .Values.GACRedentialsDir }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.connectionName }}=tcp:{{ .Values.databasePort }}"
            - "-credential_file={{ .Values.GACRedentialsPath }}"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          volumeMounts:
          - name: service-account
            mountPath: {{ .Values.GACRedentialsDir }}
            readOnly: true
      {{- with (default .Values.worker.nodeSelector .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
